### ISSUE TITLE
Filteren omzetten naar mongoose

### ISSUE THREAD

**Issue by yelizerbas** [yelizerbas/boekenzoeker#10]
Ik heb nu een schema gemaakt voor mijn filter functie om het om te zetten naar mongoose, maar zou iemand kunnen helpen met hoe ik het filteren om kan zetten naar mongoose. Ik heb niet eerder met mongoose gewerkt.

**Comment by Inevdhoven** [comment]
Ja zullen we daar vrijdag naar kijken?

**Comment by yelizerbas** [comment]
Is goed :)
