### ISSUE TITLE
Atomic operators

### ISSUE THREAD

**Issue by Inevdhoven** [yelizerbas/boekenzoeker#6]
Ik krijg een error wanneer ik een account wil updaten. De volgende error komt in beeld wanneer ik op opslaan klik: MongoInvalidArgumentError: Update document requires atomic operators. 

Weet iemand hoe ik dat kan oplossen?

**Comment by ybouz2** [comment]
Misschien omdat we geen mongoose gebruiken!

**Comment by Inevdhoven** [comment]
Ja door Mongoose is het nu opgelost :)
